name: build

permissions:
  # The Junit report needs write permission
  checks: write
  pull-requests: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      wiremock:
        image: wiremock/wiremock:latest-alpine
        ports: [8080]
        options: >-
          --name wiremock
          --hostname wiremock
          --health-interval 5s
          --health-timeout 2s
          --health-retries 3

    steps:
    - uses: actions/checkout@v6

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install valac ninja-build meson libgtk-4-dev libgee-0.8-dev libsoup-3.0-dev libjson-glib-dev libshumate-dev -y

    - name: Tool Versions
      run: valac --version && meson --version && ninja --version

    - name: Valac Compile
      run: valac --pkg gtk4 --pkg gee-0.8 --pkg libsoup-3.0 --pkg json-glib-1.0 --pkg shumate-1.0 src/*.vala --output=ukcrime-gtk4

    - name: Meson Compile
      run: meson setup build --reconfigure && meson compile -C build

    - name: Setup Wiremock Mappings
      uses: singingbush/setup-wiremock-stubs-action@0.1
      with:
        port: ${{ job.services.wiremock.ports['8080'] }}
        mappings: ${{ github.workspace }}/wiremock/mappings

    - name: Run Tests
      run: ninja -C build test
      env:
        WIREMOCK_PORT: ${{ job.services.wiremock.ports[8080] }}

    - name: Publish Test Report
      if: always() # always run even if the previous step fails
      uses: mikepenz/action-junit-report@v6
      with:
        report_paths: '**/build/meson-logs/testlog.junit.xml'
        comment: true

    - name: Upload Artifacts
      uses: actions/upload-artifact@v6
      with:
        name: build-artifacts
        path: ukcrime-gtk4
          # build/meson-logs/testlog.*
        retention-days: 2
        if-no-files-found: error

    - name: Output artifact ID
      run:  echo 'Artifact ID is ${{ steps.upload-artifacts.outputs.artifact-id }}'
