name: build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      wiremock:
        image: wiremock/wiremock:latest-alpine
        # ports: [8080]
        # volumes: ./wiremock:/home/wiremock:ro,z
        ports:
          - "8080:8080"
          - "8443:8443"
        volumes:
          - ./wiremock:/home/wiremock:ro,z
        # # --volume wiremock:/home/wiremock:ro,z
        options: >-
          --global-response-templating
          --disable-gzip
          --verbose
        # Set health checks to wait until wiremock has started
        # --health-cmd ""
        options: >-
          --health-interval 5s
          --health-timeout 2s
          --health-retries 3

    steps:
    - uses: actions/checkout@v6

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install valac ninja-build meson libgtk-4-dev libsoup-3.0-dev libjson-glib-dev -y

    - name: Tool Versions
      run: valac --version && meson --version && ninja --version

    - name: Valac Compile
      run: valac --pkg gtk4 --pkg libsoup-3.0 --pkg json-glib-1.0 src/*.vala --output=ukcrime-gtk4

    - name: Meson Compile
      run: meson setup build --reconfigure && meson compile -C build

    - name: Run Tests
      run: ninja -C build test
      env:
        WIREMOCK_PORT: ${{ job.services.wiremock.ports[8080] }}

