name: build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
#    - uses: actions/setup-python@v5

    - name: Install dependencies
      run: sudo apt install valac libgtk-4-dev libsoup-3.0-dev libjson-glib-dev

    - name: Vala Compiler Version
      run: valac --version

    - name: Valac Compile
      run: valac --pkg gtk4 --pkg libsoup-3.0 --pkg json-glib-1.0 src/*.vala --output=ukcrime-gtk4

    - name: Install Meson
      run: sudo apt install ninja-build meson -y

    - name: Meson Compile
      run: meson setup build --reconfigure && meson compile -C build

#    - name: Meson
#      uses: BSFishy/meson-build@v1
#      with:
#        action: build
#        directory: build
#        options: --verbose
#        meson-version: 1.7.0
#        ninja-version: 1.11.1.4
